### PR TITLE
Delete checked

### PR DESCRIPTION
**Pull request by dwood12**
Added checked item deletion functionality.

I added an array that associates if the item has been checked in the todo list.

### CODE REVIEW

**Comment by Jakeman893** [comment]
It isn't deleting the checked items

**Comment by dwood12** [comment]
Did you check off the items to delete and hit the trash icon under the Add button?

**Comment by Jakeman893** [comment]
yeah, nothing happened :(

**Comment by Jakeman893** [comment]
I did just retool the task system so its more object oriented. All that needs to happen is the checkbox needs to trigger a "toggle" function that changes the value of the Boolean value and then when the "delete all" button is clicked the list will be iterated through, getting rid of the completed item.

**Comment by Jakeman893** [comment]
Stupid weird config error over here on my part... works now though :100:

**Pull request merged**
